# Generated by Django 2.0.6 on 2018-08-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0012_settings_plural_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sort_title', models.CharField(max_length=200, verbose_name='Sort Name')),
                ('desc', models.TextField(blank=True, max_length=600, verbose_name='Description')),
                ('name', models.CharField(max_length=200, verbose_name='Series Name')),
            ],
            options={
                'verbose_name_plural': 'Reading Lists',
                'ordering': ['id', 'sort_title'],
            },
        ),
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.TextField(blank=True, max_length=700, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='readinglists',
            name='issues',
            field=models.ManyToManyField(blank=True, to='comics.Issue'),
        ),
    ]
